package:
  name: qstats
  version: "0.1"

source:
  path: ./

build:
  number: 0
  script: python setup.py install
  entry_points:
    - qstats = qstats.__main__:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - qstats
